# Generated by Django 3.2.16 on 2023-12-30 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('nickname', models.CharField(max_length=128, unique=True, verbose_name='nickname')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('price_eth', models.DecimalField(decimal_places=5, default=0.0, max_digits=10, verbose_name='price_eth')),
                ('price_dlr', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='price_dlr')),
                ('collection', models.CharField(max_length=128, verbose_name='collection')),
                ('on_sale', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='profiling.author', verbose_name='creator')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='profiling.author', verbose_name='owner')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='profiling.item', verbose_name='item'),
        ),
    ]
