# Generated by Django 3.2.16 on 2023-12-30 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='items',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='profiling.item', verbose_name='item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='collection',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='collection'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
    ]
