# Generated by Django 3.2.16 on 2024-01-06 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='collection_creator', to='profiling.author', verbose_name='Collection creator'),
            preserve_default=False,
        ),
    ]
