# Generated by Django 3.2.16 on 2024-01-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0002_collection_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='banner',
            field=models.ImageField(default='author_single/author_banner.jpg', upload_to='author_banner'),
        ),
        migrations.AddField(
            model_name='collection',
            name='banner',
            field=models.ImageField(default='collections/collection-default.jpg', upload_to='collection_banner'),
        ),
        migrations.AlterField(
            model_name='author',
            name='avatar',
            field=models.ImageField(default='author/author-default.jpg', upload_to='author_avatar'),
        ),
    ]
