# Generated by Django 3.2.16 on 2023-12-30 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0002_auto_20231230_1600'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Author', 'verbose_name_plural': 'Authors'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Item', 'verbose_name_plural': 'Items'},
        ),
        migrations.RemoveField(
            model_name='item',
            name='price_dlr',
        ),
        migrations.AlterField(
            model_name='item',
            name='creator',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='profiling.author', verbose_name='creator'),
        ),
        migrations.AlterField(
            model_name='item',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='profiling.author', verbose_name='owner'),
        ),
    ]
