# Generated by Django 3.2.16 on 2023-12-30 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0003_auto_20231230_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='items',
        ),
        migrations.AddField(
            model_name='author',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='item', to='profiling.Item', verbose_name='item'),
        ),
    ]
