# Generated by Django 3.2.16 on 2024-01-10 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0004_alter_item_on_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='likes',
            field=models.PositiveIntegerField(default=0, verbose_name='likes'),
        ),
    ]
