# Generated by Django 3.2.16 on 2023-12-30 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0007_auto_20231230_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='price_eth',
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='price_eth'),
        ),
    ]
