# Generated by Django 3.2.16 on 2023-12-30 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0008_auto_20231230_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='items',
        ),
        migrations.AddField(
            model_name='author',
            name='items',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='profiling.item', verbose_name='item'),
        ),
    ]
