# Generated by Django 3.2.16 on 2024-01-01 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0010_remove_author_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
