# Generated by Django 3.2.16 on 2024-01-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('slug', models.CharField(default='category', max_length=50)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('text', models.TextField(verbose_name='Text')),
                ('highlighted_text', models.TextField(blank=True, null=True, verbose_name='Highlighted Text')),
                ('is_published', models.BooleanField(default=True, verbose_name='Is published')),
                ('image', models.ImageField(default='post_image/default.jpg', upload_to='post_image')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Publishing date')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
    ]
