# Generated by Django 3.2.16 on 2024-01-08 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20240108_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=113, verbose_name='Title'),
        ),
    ]
