# Generated by Django 3.2.16 on 2024-01-03 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_post_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='post_image/default.jpg', upload_to='post_image'),
        ),
    ]
