# Generated by Django 3.2.16 on 2024-01-03 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
