# Generated by Django 3.2.16 on 2024-01-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20240103_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='slug',
            field=models.CharField(default='category', max_length=50),
        ),
    ]
