# Generated by Django 3.2.16 on 2024-01-11 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=50, verbose_name='event')),
                ('event_date', models.DateTimeField(auto_now_add=True, verbose_name='event date')),
                ('session_key', models.CharField(blank=True, max_length=32, null=True, verbose_name='session key')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
    ]
