# Generated by Django 3.2.16 on 2024-01-10 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='like',
            new_name='object',
        ),
    ]
