# Generated by Django 3.2.16 on 2024-01-11 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        ('profiling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='object',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='object', to='profiling.item', verbose_name='object'),
        ),
    ]
