# Generated by Django 3.2.16 on 2024-01-10 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0005_item_likes'),
        ('main', '0002_rename_like_events_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='object',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='object', to='profiling.item', verbose_name='object'),
        ),
    ]
