# Generated by Django 3.2.16 on 2024-01-11 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_alter_events_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='session_key',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='session key'),
        ),
        migrations.AlterField(
            model_name='events',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
