# Generated by Django 3.2.16 on 2024-01-12 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0002_initial'),
        ('main', '0003_events_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object', to='profiling.item', verbose_name='object'),
        ),
    ]
