# Generated by Django 3.2.16 on 2024-01-13 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='price_eth'),
        ),
    ]
