# Generated by Django 3.2.16 on 2024-01-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_transactions_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='price',
        ),
        migrations.AddField(
            model_name='transactions',
            name='event',
            field=models.CharField(default='transaction', max_length=50, verbose_name='event'),
        ),
        migrations.AddField(
            model_name='transactions',
            name='number',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='eth'),
        ),
    ]
