# Generated by Django 3.2.16 on 2024-01-13 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0002_initial'),
        ('main', '0007_auto_20240113_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t_object', to='profiling.item', verbose_name='object'),
        ),
    ]
