# Generated by Django 3.2.16 on 2024-01-20 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_transactions_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='watch_status',
            field=models.BooleanField(default=False, verbose_name='stats'),
        ),
    ]
