# Generated by Django 3.2.16 on 2024-01-20 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0009_events_watch_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='user_receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_receiver', to=settings.AUTH_USER_MODEL, verbose_name='user_receiver'),
        ),
    ]
